runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: assets
  secure: always

- url: /.*
  script: main.app
  secure: always

libraries:
- name: jinja2
  version: "2.6"
- name: ssl
  version: latest
